/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIElements.itemCards;

/**
 *
 * @author shubh
 */
public class itemCardsMenu extends javax.swing.JPanel {

    /**
     * Creates new form itemCardsMenu
     */
    public itemCardsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        winebliss3 = new GUIElements.itemCards.winebliss();
        eggs1 = new GUIElements.itemCards.eggs();
        avacadoes1 = new GUIElements.itemCards.avacadoes();
        honey1 = new GUIElements.itemCards.honey();
        pasta1 = new GUIElements.itemCards.pasta();
        fbasket1 = new GUIElements.itemCards.fbasket();
        loaf1 = new GUIElements.itemCards.loaf();
        fillets1 = new GUIElements.itemCards.fillets();
        quinoa1 = new GUIElements.itemCards.quinoa();
        coffee1 = new GUIElements.itemCards.coffee();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane2.setLayout(new java.awt.GridLayout(10, 0, 5, 10));
        jLayeredPane2.add(winebliss3);
        jLayeredPane2.add(eggs1);
        jLayeredPane2.add(avacadoes1);
        jLayeredPane2.add(honey1);
        jLayeredPane2.add(pasta1);
        jLayeredPane2.add(fbasket1);
        jLayeredPane2.add(loaf1);
        jLayeredPane2.add(fillets1);
        jLayeredPane2.add(quinoa1);
        jLayeredPane2.add(coffee1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 3880, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIElements.itemCards.avacadoes avacadoes1;
    private GUIElements.itemCards.coffee coffee1;
    private GUIElements.itemCards.eggs eggs1;
    private GUIElements.itemCards.fbasket fbasket1;
    private GUIElements.itemCards.fillets fillets1;
    private GUIElements.itemCards.honey honey1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private GUIElements.itemCards.loaf loaf1;
    private GUIElements.itemCards.pasta pasta1;
    private GUIElements.itemCards.quinoa quinoa1;
    private GUIElements.itemCards.winebliss winebliss3;
    // End of variables declaration//GEN-END:variables
}
