/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIElements;

/**
 *
 * @author shubh
 */
public class itemMenu extends javax.swing.JPanel {

    /**
     * Creates new form itemMenu
     */
    public itemMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        itemCards25 = new GUIElements.itemCards();
        itemCards24 = new GUIElements.itemCards();
        itemCards23 = new GUIElements.itemCards();
        itemCards22 = new GUIElements.itemCards();
        itemCards21 = new GUIElements.itemCards();
        itemCards20 = new GUIElements.itemCards();
        itemCards19 = new GUIElements.itemCards();
        itemCards18 = new GUIElements.itemCards();
        itemCards17 = new GUIElements.itemCards();
        itemCards16 = new GUIElements.itemCards();
        itemCards15 = new GUIElements.itemCards();
        itemCards14 = new GUIElements.itemCards();
        itemCards13 = new GUIElements.itemCards();
        itemCards12 = new GUIElements.itemCards();
        itemCards11 = new GUIElements.itemCards();
        itemCards10 = new GUIElements.itemCards();
        itemCards9 = new GUIElements.itemCards();
        itemCards8 = new GUIElements.itemCards();
        itemCards7 = new GUIElements.itemCards();
        itemCards6 = new GUIElements.itemCards();
        itemCards5 = new GUIElements.itemCards();
        itemCards4 = new GUIElements.itemCards();
        itemCards3 = new GUIElements.itemCards();
        itemCards2 = new GUIElements.itemCards();
        itemCards1 = new GUIElements.itemCards();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.GridLayout(25, 0, 0, 15));
        jLayeredPane1.add(itemCards25);
        jLayeredPane1.add(itemCards24);
        jLayeredPane1.add(itemCards23);
        jLayeredPane1.add(itemCards22);
        jLayeredPane1.add(itemCards21);
        jLayeredPane1.add(itemCards20);
        jLayeredPane1.add(itemCards19);
        jLayeredPane1.add(itemCards18);
        jLayeredPane1.add(itemCards17);
        jLayeredPane1.add(itemCards16);
        jLayeredPane1.add(itemCards15);
        jLayeredPane1.add(itemCards14);
        jLayeredPane1.add(itemCards13);
        jLayeredPane1.add(itemCards12);
        jLayeredPane1.add(itemCards11);
        jLayeredPane1.add(itemCards10);
        jLayeredPane1.add(itemCards9);
        jLayeredPane1.add(itemCards8);
        jLayeredPane1.add(itemCards7);
        jLayeredPane1.add(itemCards6);
        jLayeredPane1.add(itemCards5);
        jLayeredPane1.add(itemCards4);
        jLayeredPane1.add(itemCards3);
        jLayeredPane1.add(itemCards2);
        jLayeredPane1.add(itemCards1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIElements.itemCards itemCards1;
    private GUIElements.itemCards itemCards10;
    private GUIElements.itemCards itemCards11;
    private GUIElements.itemCards itemCards12;
    private GUIElements.itemCards itemCards13;
    private GUIElements.itemCards itemCards14;
    private GUIElements.itemCards itemCards15;
    private GUIElements.itemCards itemCards16;
    private GUIElements.itemCards itemCards17;
    private GUIElements.itemCards itemCards18;
    private GUIElements.itemCards itemCards19;
    private GUIElements.itemCards itemCards2;
    private GUIElements.itemCards itemCards20;
    private GUIElements.itemCards itemCards21;
    private GUIElements.itemCards itemCards22;
    private GUIElements.itemCards itemCards23;
    private GUIElements.itemCards itemCards24;
    private GUIElements.itemCards itemCards25;
    private GUIElements.itemCards itemCards3;
    private GUIElements.itemCards itemCards4;
    private GUIElements.itemCards itemCards5;
    private GUIElements.itemCards itemCards6;
    private GUIElements.itemCards itemCards7;
    private GUIElements.itemCards itemCards8;
    private GUIElements.itemCards itemCards9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
